apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: crop-disease-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
  - host: crop-disease.local
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: crop-disease-service
            port:
              number: 80